### ISSUE TITLE
Hi i tried ur Python file but its giving me some issues, care to help?

### ISSUE THREAD

**Issue by jomeen342** [billzhong/baidupan#4]
i tried this example but it gave me an error and im not sure if i made a mistake or the file is not working. 

C:\Users\***\Downloads\PY\baidupan-master\baidupan-master>baidupan.py --resume "http://pan.baidu.com/share/link?shareid=568668&uk=2987247908"
Getting html data...
Traceback (most recent call last):
  File "C:\Users\***\Downloads\PY\baidupan-master\baidupan-master\baidupan.py", line 61, in <module>
    fn = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Could u maybe help me out?

**Comment by billzhong** [comment]
This project is not longer maintained.
