### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by muhammad-tayyab** [billzhong/baidupan#5]
Getting html data...
Traceback (most recent call last):
  File "baidupan.py", line 61, in <module>
    fn = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by billzhong** [comment]
This project is not longer maintained.

**Comment by 641i130** [comment]
Then mark it as archived.

**Comment by 641i130** [comment]
Because this is still an issue.
